version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]

  backend:
    image: python:3.9-slim
    container_name: backend
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    working_dir: /app
    ports:
      - "8000:8000"  # Exposes backend on host port 8000
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: >
      bash -c "pip install --no-cache-dir -r requirements.txt &&
               python3 main.py"
    depends_on:
      - redis

  frontend:
    image: node:16-alpine
    container_name: frontend
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Prevents host's node_modules from overwriting container's
    working_dir: /app
    ports:
      - "3000:3000"  # Exposes frontend on host port 3000
    command: >
      sh -c "npm install &&
             npm run build &&
             npx serve -s build -l 3000"
    depends_on:
      - backend

volumes:
  redis-data: